### PR TITLE
Created a proper master XDC file for the FK.

### PR DESCRIPTION
**Pull request by OhGodAPet**
Ditto.

### CODE REVIEW

**Comment by d953i** [comment]
Did you try to build project with proposed constraints file?

**Review by d953i — CHANGES_REQUESTED** [review]
Sys clock is 200MHz not 300

**Comment by OhGodAPet** [comment]
> Sys clock is 200MHz not 300

If so, you may wanna check your pins XML file!

**Comment by OhGodAPet** [comment]
> > Sys clock is 200MHz not 300
> 
> If so, you may wanna check your pins XML file!

Weird... the pins file is right. Fixing!

**Pull request merged**
